### 标量

In [2]:
import torch
y = torch.tensor(3.0)
x = torch.tensor(5.0)
print((x+y),(y - x),(y * x),(y/x))

tensor(8.) tensor(-2.) tensor(15.) tensor(0.6000)


### 向量
人们通过一维张量表示向量。一般来说，张量可以具有任意长度，取决于机器的内存限制。

In [12]:
x = torch.arange(6)
x

tensor([0, 1, 2, 3, 4, 5])

我们可以使用下标来引用向量的任一元素

In [15]:
x[:]

tensor([0, 1, 2, 3, 4, 5])

### 长度、维度和形状

In [16]:
len(x)

6

In [18]:
x.shape

torch.Size([6])

### 矩阵

In [27]:
A = torch.arange(20).reshape(5,4)
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [29]:
B = torch.tensor([[1,2,3], [4,5,6], [3,2,0]])
B

tensor([[1, 2, 3],
        [4, 5, 6],
        [3, 2, 0]])

In [30]:
#转置
B == B.T

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])

### 张量

In [35]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

### 张量算法的基本性质

In [38]:
A = torch.arange(20,dtype=torch.float32).reshape(4,5)
B = A.clone()
A, A+B,A*B

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.,  8.],
         [10., 12., 14., 16., 18.],
         [20., 22., 24., 26., 28.],
         [30., 32., 34., 36., 38.]]),
 tensor([[  0.,   1.,   4.,   9.,  16.],
         [ 25.,  36.,  49.,  64.,  81.],
         [100., 121., 144., 169., 196.],
         [225., 256., 289., 324., 361.]]))

**将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘。**

In [65]:
a = 2
X = torch.arange(24).reshape(2,3,4)
X * a 

tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])

### 降维

In [71]:
x = torch.arange(4,dtype=torch.float32)
x , x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [73]:
A.shape,A.sum()

(torch.Size([4, 5]), tensor(190.))

In [76]:
B = A.sum(axis=0)
B,B.shape,A

(tensor([30., 34., 38., 42., 46.]),
 torch.Size([5]),
 tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]))

In [77]:
A.mean(),A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

### 非降维求和

In [78]:
sum_A = A.sum(axis=1,keepdims=True)
sum_A

tensor([[10.],
        [35.],
        [60.],
        [85.]])

In [79]:
A / sum_A

tensor([[0.0000, 0.1000, 0.2000, 0.3000, 0.4000],
        [0.1429, 0.1714, 0.2000, 0.2286, 0.2571],
        [0.1667, 0.1833, 0.2000, 0.2167, 0.2333],
        [0.1765, 0.1882, 0.2000, 0.2118, 0.2235]])

**如果我们想沿某个轴计算A元素的累积总和， 比如axis=0（按行计算），可以调用cumsum函数。 此函数不会沿任何轴降低输入张量的维度。**

In [80]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  7.,  9., 11., 13.],
        [15., 18., 21., 24., 27.],
        [30., 34., 38., 42., 46.]])

### 点积

In [82]:
y = torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [84]:
torch.sum(x*y)

tensor(6.)

### 矩阵-向量积

In [0]:
A.shape, x.shape,

In [107]:
A = A.reshape(5,4)
torch.mv(A,x)

tensor([ 14.,  38.,  62.,  86., 110.])

### 矩阵乘法

In [119]:
B = torch.ones(4,3)
A,torch.mm(A,B)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

### 范数

In [124]:
# L2范数
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [126]:
# L1范数
torch.abs(u).sum()

tensor(7.)

In [127]:
# Frobenius范数
torch.norm(torch.ones(4,9))

tensor(6.)

In [137]:
B = torch.arange(24).reshape(2,3,4)
len(B)

2