In [2]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [19]:
x.requires_grad_(True)
x.grad

tensor([0., 1., 4., 9.])

In [20]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [25]:
y.backward()
x.grad

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [6]:
x.grad == 4 * x

tensor([True, True, True, True])

### 现在计算x的另一个函数。

In [8]:
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [18]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()

x.grad == u 

tensor([True, True, True, True])

### Python控制流的梯度计算

In [12]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size = (), requires_grad=True)
d = f(a)
d.backward()

In [14]:
a.grad == d/ a

tensor(True)