## 不带参数的层

In [3]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, X):
        return X - X.mean()
    
lay = CenteredLayer()
lay(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [5]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [10]:
Y = net(torch.rand(4,8))
Y.mean()

tensor(-7.4506e-09, grad_fn=<MeanBackward0>)

## 带参数层

In [84]:
class Mylinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

### 实例化模型访问参数

In [102]:
linear = Mylinear(5,3)
linear.weight

Parameter containing:
tensor([[-0.8025, -0.2613,  1.5471],
        [ 1.8941, -0.7832, -0.2376],
        [ 0.0879,  1.1717,  0.9088],
        [-0.1999, -1.5677, -0.4511],
        [ 0.8873, -0.3356,  0.1916]], requires_grad=True)

### 使用自定义层直接执行前向传播计算。
生成的数据'X'为两行五列的数据，意识是为两个样本批次，每个样本5个特征，满足在Mylinear层定义的in_units=5,
在输出的时候会输出3个样本特征为‘units’=3，两个批次

In [109]:
linear(torch.rand(2, 5))


tensor([[1.8377, 0.0000, 0.0000],
        [2.7801, 0.0000, 0.0000]])

### 使用自定义层构建模型，就像使用内置的全连接层一样使用自定义层。

In [99]:
net = nn.Sequential(Mylinear(64, 8), Mylinear(8, 1))
net(torch.rand(2,64))

tensor([[0.4614],
        [6.7438]])